name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 147.93.23.184
          username: u406313474
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          source: ".,!.git,!.github,!gh_cli,!gh.zip,!curl_output.html,!pipeline.txt,!live_site_screenshot.png"
          target: "domains/ashwanitrading.digitalrubix.site/public_html"
          strip_components: 0
          rm: false
          overwrite: true
